### PR TITLE
Implementation of MIDI Pass Thru

### PR DESCRIPTION
**Pull request by AtoVproject**
All midi messages sent to USB MIDI is transmitted to Serial MIDI.

Successsfully tested on Teensy3.2 and Teensy LC builds

### CODE REVIEW

**Comment by infovore** [comment]
I like the look of this. However, I'd prefer to move MIDI Thru config to being a config byte in both the editor and the EEPROM, with a factory default to off. How would that sound to you? I can probably take on that work myself over the holidays.

**Comment by AtoVproject** [comment]
Hey!

Sounds great to me! I wanted to implement that but I don't know much about
sysex. That's why the handlers are under the control of a variable.

Thanks a lot,

Let me know if you need anything.
Cheers

**Comment by infovore** [comment]
Cool. I'll continue work in this PR and you can see how I'm going about it.

**Comment by infovore** [comment]
OK! I've taken a `patch` of this and applied it (so you get appropriate credit in the logs).

Next up, I'm going to [continue working in a new PR](https://github.com/16n-faderbank/16n/pull/52) and convert your code to something the web editor will be able to toggle. I'm going to close this as a result and move over there.

**Comment by AtoVproject** [comment]
Thanks a lot for the mention and the inclusion of my small contribution!

**Comment by infovore** [comment]
@AtoVproject but of course - it's a nice inclusion, and your contributions to the project have been appreciated!

**Pull request closed without merging**
